services:
  - type: web
    name: kkphim-stremio-addon
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /manifest.json
    envVars:
      - key: NODE_ENV
        value: production
